@echo off
set RELEASE_KEYSTORE_PASSWORD=android
set RELEASE_KEYSTORE_ALIAS=release
set RELEASE_KEY_PASSWORD=android
echo RELEASE_KEYSTORE_PASSWORD=%RELEASE_KEYSTORE_PASSWORD%
echo RELEASE_KEYSTORE_ALIAS=%RELEASE_KEYSTORE_ALIAS%
echo RELEASE_KEY_PASSWORD=%RELEASE_KEY_PASSWORD%
call gradlew.bat assembleRelease --no-daemon
